### ISSUE TITLE
Measurements button in data browser is broken

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#139]
It uses the old filtering API URL, e.g. https://xronos.ch/table?utf8=%E2%9C%93&query_site=Svinavath.

It should be changed to e.g. https://xronos.ch/data?utf8=✓&filter[sites][name][]=Svinavath 

But we'll also need to some JS to focus on the table instead of the map.

I wonder if we could also clarify the text of the button while we're at it, perhaps something like "Filter xrons..." ?

**Comment by MartinHinz** [comment]
I am actually not sure if we need that button at all? Reducing complexity from the frontend is never a bad thing, and I have not really missed that button. What do you think, should we remove that disabled lines fully and consider this as closed?

**Comment by joeroe** [comment]
I agree. If you go to the site view you see all the c14 measurements listed anyway.
