### ISSUE TITLE
'Clicking off' site popups breaks the data browser

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#158]
Steps to reproduce:

1. Open https://xronos.ch/data
2. Click on a site to open its popup
3. Click away from the site to close the popup again
4. Try to pan or zoom the map or open another popup.
5. Leaflet no longer responds properly

@MartinHinz was this perhaps introduced with the switch to supercluster in 06f4c98d622633e6740621a54b49c57e42829597?

**Comment by MartinHinz** [comment]
Very likely you are right! Should be solved with ebed5a8f742c1040aec2e30b82c2f247fb66dfa3. @joeroe, please check on your environment and mark solved if it works for you.

**Comment by joeroe** [comment]
Fixed in ebed5a8f742c1040aec2e30b82c2f247fb66dfa3
