### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#183]
https://keepachangelog.com/en/1.0.0/

**Comment by MartinHinz** [comment]
Agreed, should be (best) practice for every new release from now onwards. Is this an actionable item/issue beyond doing this?

**Comment by joeroe** [comment]
It goes hand in hand with https://semver.org I suppose.

**Comment by joeroe** [comment]
Added in 0a6f3fa58f0f7adc57c97668b10c4c401cafbf9f
