### ISSUE TITLE
Server Logs: routing Error "/index.php/dendrochronology"

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#204]
Like so:

```
I, [2023-02-07T18:11:34.729792 #121]  INFO -- : [56b3b143-85eb-4031-bd3f-f44216482585] Started GET "/index.php/dendrochronology/" for 85.25.185.103 at 2023-02-07 18:11:34 +0000
F, [2023-02-07T18:11:34.783035 #121] FATAL -- : [56b3b143-85eb-4031-bd3f-f44216482585]   
[56b3b143-85eb-4031-bd3f-f44216482585] ActionController::RoutingError (No route matches [GET] "/index.php/dendrochronology"):
[56b3b143-85eb-4031-bd3f-f44216482585]  
```

**Comment by joeroe** [comment]
Looks like this is from a bad link on the WordPress site: https://blog.xronos.ch/index.php/radiocarbon-dating/

There is a reciprocal one here: https://blog.xronos.ch/index.php/dendrochronology/

I didn't even know we had these pages (they don't appear to having any incoming links?)  and in general have always seen Wordpress as a temporary solution until we can get this kind of things into the Rails app (#160).
