### ISSUE TITLE
uncal BP filter in data browser not giving expected result

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#307]
For example, [filtering between 35000 and 50000 BP](https://xronos.ch/data?utf8=%E2%9C%93&filter%5Bsites%5D%5Bname%5D%5B%5D=&filter%5Bsite_types%5D%5Bname%5D%5B%5D=&filter%5Bsites%5D%5Bcountry_code%5D%5B%5D=&filter%5Bmaterials%5D%5Bname%5D%5B%5D=&filter%5Btaxons%5D%5Bname%5D%5B%5D=&filter%5Bc14_labs%5D%5Bname%5D%5B%5D=&filter%5Bc14s%5D%5Blab_identifier%5D%5B%5D=&filter%5Bc14s%5D%5Bbp%5D%5B%5D=35000.00&filter%5Bc14s%5D%5Bbp%5D%5B%5D=50000.00&filter%5Bc14s%5D%5Bbp%5D%5B%5D=0&filter%5Bc14s%5D%5Bbp%5D%5B%5D=50000&button=) returns 349663 of 350190 records.

**Comment by MartinHinz** [comment]
There are several dates with `bp > 50000`:

1158, 17851, 17852, 17853, 89245, 110893, 110894, 133160, 133161, 133162, 133431, 133432, 134031, 134788, 135445, 137769, 137770, 143885, 143886, 143887, 144240, 146025, 167998, 168000, 168001, 168003, 168010, 168011, 168012, 169977, 169978, 254482, 284378, 290902, 291856, 293070, 298859, 300472, 301008, 336619, 337911, 341138, 342116, 342117, 342118, 236992, 290311, 291570, 331792, 331793, 120936, 120951, 133953, 134579, 134580, 135624, 135987, 135988, 136968, 137609, 137985, 138331, 179254, 179256, 241465, 250236, 290459, 291400, 291410, 291529, 291530, 292488, 293644, 293645, 299292, 336414

and some with `bp < 0`:

143777, 143778, 143779, 143780

That might explain the difference?

**Comment by joeroe** [comment]
I think the problem is with the form controls: whatever you choose, an additional set of GET parameters are created (`filter[c14s][bp][]=0&filter[c14s][bp][]=50000`). If you manually remove these from the address, the correct set of results is returned.

**Comment by joeroe** [comment]
@MartinHinz This is fixed now, right?

**Comment by MartinHinz** [comment]
Loved with [64b62d6](https://github.com/xronos-ch/xronos.rails/commit/64b62d6116a3876e32ae1f2937bdaddfc5e43a0d)
