### ISSUE TITLE
'Show data filter' button is not tethered to the data

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#38]
It floats over the whole page, which to me at least is unintuitive. I'd expect it to be tethered to the block that shows the actual data (e.g. map, table).

**Comment by MartinHinz** [comment]
That is true. My plan is to attach it rather to the left border of the page, acting as a drawer. But I was not able up to now to make this work.

Alternatively, as you suggest, for the table the button could be below the table, but for the map I do not see an obvious spot to put it. Do you have a suggestion?

**Comment by joeroe** [comment]
Floating over one of the corners of the map itself? But I suggest a wider shake-up as part of #45.

**Comment by MartinHinz** [comment]
attached buttons to table and within map with 91ac93e358fdc94ad4d9490457c67473f88c1861. Still, #45 remains important.

Please check when staging is updated, and close issue if you approve.
