### ISSUE TITLE
'Select all dates' only selects the currently displayed page

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#44]
Not exactly a bug, but could perhaps be made clearer – and do we want to make it possible to select all dates across pages?

I like the way Gmail does this, with a select all/none button embedded in the table itself:

![screenshot-20210824111453](https://user-images.githubusercontent.com/6751089/130591417-720ab737-62ed-4f7f-9109-d315be77cfcc.png)

The drop-down menu this opens could include separate options for 'select all' and 'select all on page' or 'select all visible'. And/or we could show an explicit message, also like Gmail:

![screenshot-20210824111505](https://user-images.githubusercontent.com/6751089/130591413-5c908ed2-5283-41ec-87d3-91f67f1f0452.png)

**Comment by MartinHinz** [comment]
For the time being, I implemented a checkbox checking all items in view. Given the current options from the button menu, I honestly do not see a use case for "checking" all entries?

**Comment by joeroe** [comment]
If you want to calibrate/sum more than 20 dates at a time?

**Comment by MartinHinz** [comment]
I am not sure if I want the user to do this (calibrating all 42560?).

**Comment by joeroe** [comment]
Yeah for sure there should be a limit, although for the sum calibration tool to be useful, it should surely be considerably larger than 20? But maybe this is an issue that we will address when we come to making a dedicated analysis view?

**Comment by joeroe** [comment]
No longer relevent since we don't have lasso selection (#138) or sum calibration (#328) functionality any more, but should bear this problem in mind if/when we reimplement those.
