### ISSUE TITLE
Add instructions for setting up a dev environment to README

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#61]
i.e. a dockerless server setup. Something like:

1. Install external dependencies: ruby, bundler, yarn, postgresql
2. Set up postgresql: create a xronos user with CREATEDB privileges
3. Fill in `env_variables.env` and move it to `./.env`
4. Run `bundle && yarn` to install dependencies
5. Run `bin/rails db:setup` to set up and seed the database
6. Start a dev server with `bin/dev`*

\* If there's an error about missing foreman, restart your terminal.

**Comment by joeroe** [comment]
Having now done this for the third or fourth time, I think I've figured out a smooth set of instructions (above). @MartinHinz could you check whether there's anything stupid/unnecessary? Then I will add to the README so I don't have to puzzle it out again next time!

**Comment by MartinHinz** [comment]
At first glance, this looks correct and complete to me. If this is how it worked for you for the third time, it should also be correct ;-) I would have said, not such a high priority, but if it is going to be helpful for yourself, then go ahead!

**Comment by joeroe** [comment]
Would need to be revised if/when we move from webpacker #83.

**Comment by joeroe** [comment]
Updated the instructions, which work quite smoothly for me.
