### ISSUE TITLE
Should all models have a name attribute?

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#66]
It would be quite useful to rely on all models having a `name` attribute which can be used to concisely describe them.

Most do, except:

* `arch_object`
* `on_site_object_position`
* `reference`
* `sample`
* `measurement`
* `c14_measurement`

**Comment by MartinHinz** [comment]
I see the point, but for those it might be difficult to come up with a reasonable one? Do you have suggestions for the content of the "name" for these?

**Comment by joeroe** [comment]
Well it could always be the ID, as a last resort. Otherwise for things like c14_measurement it could be a compound of other fields, e.g. `bp + '±' + std`. In fact it might be more robust to make this a `friendly_identifier` method for all models?
