### ISSUE TITLE
Firefox - Data Points on Map not visible

### ISSUE THREAD

**Issue by carolineheitz** [xronos-ch/xronos.rails#9]
The title says it all. Screenshot here:
![Bildschirmfoto 2019-09-11 um 14 10 57](https://user-images.githubusercontent.com/30797678/64696214-26a85c80-d49e-11e9-81d8-61288b99edb9.png)

**Comment by nevrome** [comment]
I can not reproduce this error. Neither locally in my development environment, nor when I log into the Uni Bern network via VPN and access http://xronos.iaw.unibe.ch/. I'm on Firefox version 69.0 (64-bit). 

![Screenshot_2019-09-11_16-22-31](https://user-images.githubusercontent.com/10789038/64705707-ab03db00-d4b0-11e9-8228-b60ad3a8476b.png)

1. Can you try to update your Firefox version if it's outdated?
2. Are the dates only missing on the map or also in the table on the left?
3. Is there a meaningful console message?

**Comment by carolineheitz** [comment]
Firefox is alraedy the newest version, data is not missin in the table...we opend the console and pressed F5 (magic trick) and data was there... even after restarting firefox. And we do not know why...

**Comment by nevrome** [comment]
Hm. Neither do I. There's nothing in the console?

**Comment by carolineheitz** [comment]
Nope. However, [https://www.spektrum.de/rezension/das-nichts-verstehen/1054182](url) ;-) ...

**Comment by MartinHinz** [comment]
Solved somewhen during the update process...
