### ISSUE TITLE
Generalise the map

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#94]
At the moment the leaflet map is hard-coded with settings for the view at <https://xronos.ch/map>. But we already use it in different views, e.g. https://xronos.ch/sites/12613, where these are less appropriate and cause problems (#88). In the future it would be useful to use it more contexts, e.g. to provide an interface for selecting coordinates in forms.

We should generalise the map as a module or stimulus controller (#83) with configurable options. This would allow us to choose more appropriate settings, e.g. setting a fixed zoom and removing controls in the site show view.

Relatedly, it would make it easier to add more user-configurable options, like showing or hiding labels on the base map.

**Comment by MartinHinz** [comment]
That is a good point! It sounds to me like a module is the right approach here. Putting this in a controller, I think, contradicts the Rails logic.
